//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Staff()
        {
            this.tbl_Appointment = new HashSet<tbl_Appointment>();
            this.tbl_Appointment1 = new HashSet<tbl_Appointment>();
            this.tbl_ImagingOrder = new HashSet<tbl_ImagingOrder>();
            this.tbl_ImagingOrder1 = new HashSet<tbl_ImagingOrder>();
            this.tbl_InjectionOrder = new HashSet<tbl_InjectionOrder>();
            this.tbl_InjectionOrder1 = new HashSet<tbl_InjectionOrder>();
            this.tbl_LaboratoryOrder = new HashSet<tbl_LaboratoryOrder>();
            this.tbl_LaboratoryOrder1 = new HashSet<tbl_LaboratoryOrder>();
            this.tbl_PatientHistory = new HashSet<tbl_PatientHistory>();
            this.tbl_Prescription = new HashSet<tbl_Prescription>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string JobTitle { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> SubCity { get; set; }
        public string Woreda { get; set; }
        public string AccountID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> RegStatus { get; set; }
        public Nullable<int> Department { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointment> tbl_Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointment> tbl_Appointment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ImagingOrder> tbl_ImagingOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ImagingOrder> tbl_ImagingOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InjectionOrder> tbl_InjectionOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InjectionOrder> tbl_InjectionOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LaboratoryOrder> tbl_LaboratoryOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LaboratoryOrder> tbl_LaboratoryOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PatientHistory> tbl_PatientHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prescription> tbl_Prescription { get; set; }
        public virtual tbl_SubCity tbl_SubCity { get; set; }
    }
}
