//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImagingOrder
    {
        public int ID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> ImagingID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte[] ImageResult { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual tbl_OrderStatus tbl_OrderStatus { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
        public virtual tbl_Staff tbl_Staff { get; set; }
        public virtual tbl_Staff tbl_Staff1 { get; set; }
    }
}
