//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Woreda
    {
        public int ID { get; set; }
        public string Woreda { get; set; }
        public Nullable<int> SubCityID { get; set; }
    
        public virtual tbl_SubCity tbl_SubCity { get; set; }
    }
}
